### ISSUE TITLE
Grid in example does not render

### ISSUE THREAD

**Issue by LegNeato** [ForesightMiningSoftwareCorporation/bevy_infinite_grid#11]
`cargo run --release --example simple` on a M1 mac. Bevy's examples work on this system.

On load, shows nothing:

<img width="1392" alt="Screen Shot 2022-10-18 at 3 56 49 PM" src="https://user-images.githubusercontent.com/368904/196531412-eeea17ab-04e2-420c-aaa3-a4db1fd078f6.png">

Navigating around I get cubes but no grid:

<img width="1392" alt="Screen Shot 2022-10-18 at 3 57 17 PM" src="https://user-images.githubusercontent.com/368904/196531578-6633078e-5d3c-4269-b014-9b707675eca4.png">

**Comment by malwrar** [comment]
Encountered the same issue. Turns out the grid is there, the camera just [starts at y=0](https://github.com/ForesightMiningSoftwareCorporation/bevy_infinite_grid/blob/main/examples/simple.rs#L29) which makes it invisible. Pressing space will make it visible.
