### ISSUE TITLE
Camera2dBundle

### ISSUE THREAD

**Issue by Vixeliz** [ForesightMiningSoftwareCorporation/bevy_infinite_grid#18]
I was wondering if it's possible to use this i've tried rotating it on the x axis so hopefully it would show up but it did not. Is it just not possible? Awesome library btw!

**Comment by TheRawMeatball** [comment]
This library is intended for use in 3D applications and doesn't support 2D, and likely won't given how overkill it'd be. For 2D where you don't need to deal with things like perspective, just overlaying an image of a grid and seamlessly teleporting it so the camera can always see it would both be simpler and perform better.
