### ISSUE TITLE
Update to bevy 0.10

### ISSUE THREAD

**Issue by rlidwka** [ForesightMiningSoftwareCorporation/bevy_infinite_grid#19]
`bevy_flycam` dev dependency is not updated yet

I've tried to update, see this commit: https://github.com/rlidwka/bevy_infinite_grid/commit/48d1b7cf3759e0331b796c3e6a57882a0867b464

`EntityRenderCommand` is merged into `RenderCommand` (biggest change here), stages are replaced with system sets, and so on

It compiles, but returns real-time errors which I don't know how to debug. Can anyone help?

**Comment by PikminGuts92** [comment]
I'm in the same situation. I was able to get it compiling and the example running. However, the infinite grid does not display and there's runtime errors. This is the branch I made. Looks like we made similar changes. https://github.com/PikminGuts92/bevy_infinite_grid/tree/bevy-0.10

My error seems to be shader related. I suspect it might be my `RenderCommand` implementations as migrating from `EntityRenderCommand` was unclear to me. https://github.com/bevyengine/bevy/pull/6885

<img width="961" alt="simple_example" src="https://user-images.githubusercontent.com/15707039/226493340-058efe20-6635-4532-902c-763fd14e4656.png">

```
2023-03-21T00:20:56.236287Z ERROR bevy_render::render_resource::pipeline_cache: failed to process shader:
error: expected expression, found '#'
   ┌─ wgsl:57:41
   │
57 │     cascades: array<DirectionalCascade, #{MAX_CASCADES_PER_LIGHT}>,
   │                                         ^ expected expression


2023-03-21T00:20:56.242526Z ERROR bevy_render::render_resource::pipeline_cache: failed to process shader:
error: redefinition of `derivative`
    ┌─ wgsl:107:9
    │
107 │     let derivative = fwidth(coord);
    │         ^^^^^^^^^^ previous definition of `derivative`
    ·
114 │     let derivative = fwidth(coord * 0.1);
    │         ^^^^^^^^^^ redefinition of `derivative`


2023-03-21T00:20:56.355695Z ERROR bevy_render::render_resource::pipeline_cache: failed to process shader:
error: redefinition of `derivative`
    ┌─ wgsl:107:9
    │
107 │     let derivative = fwidth(coord);
    │         ^^^^^^^^^^ previous definition of `derivative`
    ·
114 │     let derivative = fwidth(coord * 0.1);
    │         ^^^^^^^^^^ redefinition of `derivative`
```

**Comment by PikminGuts92** [comment]
@rlidwka looks like my PR was merged in yesterday. There's also new release on crates.io so presumably the changes are in there.
