### ISSUE TITLE
Debug lines will not shown if under plane

### ISSUE THREAD

**Issue by piaoger** [ForesightMiningSoftwareCorporation/bevy_infinite_grid#29]
Thanks for the upgrade. After migrate to new version, I found debug lines will be clipped but meshes not.Please see below screenshots for more details:
 
### After move the new version:

- with bevy gizmo sample
 
![infinite_grid_2](https://github.com/ForesightMiningSoftwareCorporation/bevy_infinite_grid/assets/179429/da4f3ccf-d828-40a0-9c62-449232fe79bb)

- with bevy-repier example(debug render used)

![infinite_grid](https://github.com/ForesightMiningSoftwareCorporation/bevy_infinite_grid/assets/179429/ae16f89d-db0d-43f7-97ab-ceeb07580bb9)

### In old version:

- with bevy-repier example(debug render used)

![ddb499872fb6f9caff8a15019899608](https://github.com/ForesightMiningSoftwareCorporation/bevy_infinite_grid/assets/179429/f71410d2-8676-464c-9406-725874108e8d)

**Comment by tachimarten** [comment]
This also affects `bevy_hanabi` particles.
