### ISSUE TITLE
Update crate releases for bevy 0.12

### ISSUE THREAD

**Issue by matte1** [ForesightMiningSoftwareCorporation/bevy_infinite_grid#44]
I was wondering if we could cut a new release and update crates.io with the new release. I'd like to use this project through bazel and its difficult to point it at a specific git hash. If its possible for me to help with this process I would be happy to. Wonderful project for robotics!

**Comment by loispostula** [comment]
resolved by https://github.com/ForesightMiningSoftwareCorporation/bevy_infinite_grid/pull/43
