### ISSUE TITLE
Unable to build the simple example

### ISSUE THREAD

**Issue by barsoosayque** [ForesightMiningSoftwareCorporation/bevy_infinite_grid#6]
As far as I can tell, building the library assumes that you have bevy in the parent directory.
https://github.com/ForesightMiningSoftwareCorporation/bevy_infinite_grid/blob/bcc752b88ddb531443a2df9527815a10bef4c869/Cargo.toml#L23-L24

So running `cargo run --example simple` results in 
> error: failed to load source for dependency `bevy`
>
> Caused by:
> Unable to update /path/bevy
>
> Caused by:
> failed to read `/path/bevy/Cargo.toml`
>
> Caused by:
> No such file or directory (os error 2)

**Comment by TheRawMeatball** [comment]
Fixed!
