### ISSUE TITLE
How to use GridShadowCamera ?

### ISSUE THREAD

**Issue by barsoosayque** [ForesightMiningSoftwareCorporation/bevy_infinite_grid#7]
While trying to use `bevy_infinite_grid` v0.5.1, I'm getting constant crashes, although I'm doing what docs told me to do (or rather, what I copied from the simple example :smile:). Here is the crash log:

```
thread 'Compute Task Pool (3)' panicked at 'called `Result::unwrap()` on an `Err` value:
NoEntities("bevy_ecs::query::state::QueryState<(&bevy_transform::components::global_transform::GlobalTransform, 
&bevy_render::camera::camera::Camera), bevy_ecs::query::filter::With<bevy_infinite_grid::GridShadowCamera>>")',
src/lib.rs:134:33
```

Seems like using the library requires an entity with `GridShadowCamera`:
https://github.com/ForesightMiningSoftwareCorporation/bevy_infinite_grid/blob/bcc752b88ddb531443a2df9527815a10bef4c869/src/lib.rs#L124-L134

But I'm not really sure how I'm supposed to spawn a `GridShadowCamera` ? Do I just inject it into some other camera I'm using ?

**Comment by TheRawMeatball** [comment]
Yep, just insert the `GridShadowCamera` component into your existing primary 3d camera.

**Comment by barsoosayque** [comment]
Shouldn't the camera in `track_frustum_intersect_system` be optional ? If I use states and in the initial state I don't have a 3d camera yet (main menu), it just crashes.

**Comment by barsoosayque** [comment]
#8 fixed the issue

**Comment by barsoosayque** [comment]
Ah, it works, but requires you to spawn a `InfiniteGridBundle`, otherwise render systems will crash. Because of that, it still seems to be impossible to add the plugin and do nothing until the right state
